Repository knative-extensions/eventing-ceph, pull requests merged in 2021-12, with the labels that each got.

#181 Metric label fix
  pkg/reconciler/ceph/resources/labels.go
  pkg/reconciler/ceph/resources/receive_adapter.go
Labels: cla: yes, lgtm, approved, size/S

#179 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/M, lgtm, approved

#180 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/M, lgtm, approved

#176 Document maturity levels in sandbox
  README.md
Labels: cla: yes, lgtm, approved, size/XS

#183 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, lgtm, approved

#182 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#185 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S
