Repository knative-extensions/eventing-ceph, pull requests merged in 2022-08, with the labels that each got.

#279 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#281 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#283 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#284 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#286 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#282 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#287 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#280 upgrade to go 1.18
  go.mod
  go.sum
Labels: size/M, lgtm, approved

#289 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#290 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#292 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#291 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_configmap.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_environment.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#294 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS
