Repository knative-extensions/eventing-ceph, pull requests merged in 2023-08, with the labels that each got.

#347 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#348 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#349 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#352 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#351 Rename knative-sandbox to knative-extensions
  README.md
Labels: lgtm, approved, size/XS

#353 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
