Repository knative-extensions/eventing-ceph, pull requests merged in 2023-11, with the labels that each got.

#378 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#379 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/iam/apiv1/iampb/iam_policy.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/options.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/policy.pb.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/bucket.go
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/hmac.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/gapic_metadata.json
  vendor/cloud.google.com/go/storage/internal/apiv2/storage_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/invoke.go
  vendor/cloud.google.com/go/storage/reader.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/google.golang.org/api/internal/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#380 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#382 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#383 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#384 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#385 Make SECURITY.md consistent
  SECURITY.md
Labels: lgtm, approved, size/XS

#386 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/jwt/builder.go
  vendor/github.com/go-jose/go-jose/v3/jwt/claims.go
  vendor/github.com/go-jose/go-jose/v3/jwt/doc.go
  vendor/github.com/go-jose/go-jose/v3/jwt/errors.go
  vendor/github.com/go-jose/go-jose/v3/jwt/jwt.go
  vendor/github.com/go-jose/go-jose/v3/jwt/validation.go
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/auth/token_provider.go
  vendor/knative.dev/eventing/pkg/auth/utils.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#387 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#388 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#389 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#390 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#391 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/modules.txt
Labels: size/M, lgtm, approved
