Repository knative-extensions/eventing-ceph, pull requests merged in 2023-04, with the labels that each got.

#326 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#329 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#324 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#328 chore: migrate from k8s.gcr.io to registry.k8s.io
  config/config-observability.yaml
Labels: lgtm, approved, size/XS

#330 :dizzy: Replace removed image and bump eventing
  go.mod
  go.sum
  hack/tools.go
  vendor/knative.dev/eventing/cmd/heartbeats/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/eventing/test/test_images/heartbeats/main.go
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#332 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
