Repository knative-extensions/eventing-ceph, pull requests merged in 2023-01, with the labels that each got.

#313 Removes deprecated io.ioutil package and updates codegen for go v1.19
  pkg/adapter/adapter.go
  pkg/adapter/adapter_test.go
  pkg/apis/sources/v1alpha1/register_test.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: lgtm, approved, size/S

#311 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS, skip-review

#309 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, lgtm, approved, skip-review
